### ISSUE TITLE
Regular freeze of UI

### ISSUE THREAD

**Issue by jabby** [angelozerr/angularjs-eclipse#109]
I don't understand why but I have some problems since one week when I use the last version of AngularJS-Eclipse plugin. The UI freeze regularly and I need to kill Eclipse and to restart it. 

I notice that node process (not embedded node) take between 1 to 1,5 Go of memory. Maybe it's the real problem. Do you have the same problem or an idea to correct this behavior ?

**Comment by angelozerr** [comment]
For your information, MyEclipse has provided a great configuration to avoid freeze with completion. See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#asynch-tern-completion

**Comment by ankit2711** [comment]
I have seen the same issue(too much CPU used and eclipse hangs) while trying to include the Angular phonecat app on Eclipse Luna on Ubuntu 14.04. I was including the project code in as Javascript project. Finally I disabled the JSNature and after that converted the project to AngularJS. Now eclipse is stabler.

**Comment by angelozerr** [comment]
@ankit2711 I suggest you that you install 0.9.0 SNAPSHOT: it will avoid freezing Eclipse wjen tern completion opens (when there are a lot of JS files). 

Disable the JSNature means that tern script path will be not loaded from the JSDT Install Path, it's the reason why Eclipse doesn't freeze. Indeed, tern script path doesn't support exclude path and JSDT (by default) set the Install Path to the root project (I think it's your case). JSDT support exclude path that I must support it.

**Comment by angelozerr** [comment]
I close this issue since asynch compeltion is working. I muts just implement now exclude tern script path.
