### ISSUE TITLE
Resource '/angularjs-in-30-minutes/.tern-project' does not exist.

### ISSUE THREAD

**Issue by paulvi** [angelozerr/angularjs-eclipse#123]
I got interesting problem with `.tern-project` file 

When I open  `.tern-project` file with Editor it shoues

> Resource '/angularjs-in-30-minutes/.tern-project' does not exist.

as if it is not synced (I have autosync on access by default )

![angular122](https://cloud.githubusercontent.com/assets/1614482/5009141/044aacc4-6a9f-11e4-92ae-4bc5431b815b.PNG)

**Comment by angelozerr** [comment]
@paulvi is there again this problem?

**Comment by angelozerr** [comment]
I close this issue.
