### ISSUE TITLE
Undefined attribute name in template

### ISSUE THREAD

**Issue by nicola883** [angelozerr/angularjs-eclipse#124]
I have installed the 0.7.0 version and converted the project to angulajs project.
I see in angular explorer all the modules under directories with the path and (jsdt) at the end.
The link to the "go to definition" works well.

But in the template I cannot have any directive completation or informations about them.
I cannot see any menu "Directives" under Angularjs in properties and any "script paths" and "console" under Term so I cannot add any path.

I'm running a fresh installation of eclipse luna 4.4.1

Many thanks for your help to resolve the issue.

**Comment by angelozerr** [comment]
@nicola883 can I close this issue?

**Comment by nicola883** [comment]
Dear Angelo,
I've checked all configurations and all looks ok, but still I don't see some completation.

In my index.html (an html files with ng-app and ng-controller as you suggest to try) I see:
- completation with list of modules, for example if I write:
ng-app=... I SEE the list of the modules

But I don't see completation after:
ng-...

and no output in term console.

In myApp.js I have:

```javascript
var myApp = angular.module('myApp', [
  'ngRoute',
  'myApp.filters',
  ...
]);
```
If I do myApp.... I don't see nothing, and nothing happens in tern console.

But if I set some variables (i.e. var t = angular.module...), the Tern console has a long output:

```javascript 
{"files":[{"name":"app/js/app.js","text":"'use strict';\n\n\n// Declare app level module which depends on filters, and services\nangular.module('myApp', [\n  'ngRoute',\n  'myApp.filters' ... (very long output with list of my modules and files)

Tern response# with 4ms: 
{}
-----------------------------------
-----------------------------------
Tern request#type: 
{"query":{"type":"type","file":"app/js/app.js","end":37,"docs":true,"urls":true,"types":true,"file":"app/js/app.js"}}

Tern error#type with 81ms: 
tern.TernException: TernError: No type found at the given position.
```

My index.html has set the module (ng-app) and the controller (ng-controller) in this way:
```html
<html xmlns:ng="http://angularjs.org" id="ng-app" ng-app="myApp" >
...
<body ng-controller="topCtrl">
...
```

In the first level in Angular Explorer I see a lot of folder that ends with (jsdt) and not only the main folder that I've set with tern/scripts path as you suggest. I've tried to delete but I can't.

Many thanks for your help and sorry again for my delay to answer.

Nicola.

**Comment by angelozerr** [comment]
@nicola883 please share your project which causes your problem. I think it will be more easy to discover the problem.

Please not that 0.8.0 was released since this issue.

**Comment by angelozerr** [comment]
None answer, I close this issue.
