### ISSUE TITLE
Eclipse IDE crashes with angularjs plugin

### ISSUE THREAD

**Issue by allvisa** [angelozerr/angularjs-eclipse#141]
If I install this plugin I cannot right click my project folder in eclipse anymore. If I uninstall the plugin again everything works fine. I still installed the JBoss-Tools und Spring-Plugin before.

I am using Eclipse Luna Service Release 1a (4.4.1) and tried it with Plugin-Version 0.8 and the latest 0.9 snapshot without sucess.

Thank you in advance for your help.

**Comment by angelozerr** [comment]
JBoss-Tools have integrated tern.java and AngularJS Eclipse but I don't know which version.

Could you please install AngularJS Eclipse with a fresh Eclipse installation (without JBoss Tools)?

**Comment by angelozerr** [comment]
@allvisa have you some errors in the proble view or other?

**Comment by angelozerr** [comment]
@allvisa could you give me some info please otherwise I will close this issue. Thanks.

**Comment by angelozerr** [comment]
None answer, I close the issue.
