### ISSUE TITLE
The update site isnt working

### ISSUE THREAD

**Issue by maheshk172** [angelozerr/angularjs-eclipse#151]
Hi,

I am trying to install this plugin using update site listed on this page. 

https://github.com/angelozerr/angularjs-eclipse/wiki/Installation-Update-Site

First URL http://oss.opensagres.fr/angularjs-eclipse/0.9.0/ is not active, I cant hit this using browser as well. 

Second URL http://www.nodeclipse.org/updates/anide/SNAPSHOT/.  does not have AngularJS options listed.  

Please advise if any alternate way to install in in STS.

Regards,
Mahesh Kulkarni

**Comment by angelozerr** [comment]
> First URL http://oss.opensagres.fr/angularjs-eclipse/0.9.0/ is not active, I cant hit this using browser as well.

You cannot access to the url http://oss.opensagres.fr/angularjs-eclipse/0.9.0/ with your web browser? In my case it works?

What is your error by using Eclipse Update site?

**Comment by maheshk172** [comment]
![image](https://cloud.githubusercontent.com/assets/5226009/7273258/82097fac-e90f-11e4-9aff-e08f4218b1d3.png)

At same time, I can access other Update Sites..  for LUNA and others, so my  network connectivity is fine.  Is there any other URL I can access or download this repository ?

**Comment by angelozerr** [comment]
I don't know why you have this problem?

@paulvi @pascalleclercq have you an idea?

**Comment by paulvi** [comment]
First, recently Nodeclipse is slower then before and I suspect if it because of  http://oss.opensagres.fr hosting. Is it CDN-based?

Related issues are 
- https://github.com/angelozerr/tern.java/issues/201 "Doanload is slow and fails, offline zip option"
- https://github.com/angelozerr/tern.java/issues/271 "Build all maven projects at once", that would give one solid zip and one solid and quicker update site

**Comment by paulvi** [comment]
> First URL http://oss.opensagres.fr/angularjs-eclipse/0.9.0/ is not active, I cant hit this using browser as well.

is active and can be opened from browser

> Second URL http://www.nodeclipse.org/updates/anide/SNAPSHOT/. does not have AngularJS options listed.

there is AngularJS inside.

I am in China.

Mahesh, where are you?

**Comment by maheshk172** [comment]
Hi Paul,  

I am based in India, Pune.  It seems I had issue with my network setup.  I had some issue with my proxy it seems, in eclipse when I renamed file org.apache.httpcomponents.httpcore_4.3.3.v201411290715.jar  to org.apache.httpcomponents.httpcore_4.3.3.v201411290715.jar.old or something, the download started working. 

Does this plugin support Sprint Toolkit (STS) as well ?  I am using STS 3.6.2 and installed this plugin but I am not able to see any Angular preferences or options shown in the demo.

**Comment by angelozerr** [comment]
That's is very strange -(

Never tested to install Angular with STS. Have you tried to install with a simple Eclipse JEE distribution?

**Comment by maheshk172** [comment]
I tried mate, but same issue with that too.  Not sure if I am missing something.  I have installed using Install New Software and the Update link listed above.  Installation is successful, I can see it in Installed softwares but I do not see any preferences or menus. 

Is there any way to troubleshoot

**Comment by angelozerr** [comment]
I don't know why you have this problem? Have you some errors in the Error log View?

**Comment by paulvi** [comment]
Too much discussion in one issue.

BTW, there is nothing special about STS

**Comment by pascalleclercq** [comment]
Hi,

i uploaded the repo as a single zip here :
https://github.com/angelozerr/angularjs-eclipse/releases/tag/angularjs-eclipse-0.9.0

I have to do It manually, I'm looking for a way to do It automatically are release time.

I think I have to look for another http hosting for the update sites. 

The ones that already exists is provided from a french provider : http://www.online.net/

Not sure why you can't browse It from China.

Does anybody has a suggestion for an alternative http hosting ? (for a limited budget)

**Comment by angelozerr** [comment]
Very cool @pascalleclercq ! You are the best :)

**Comment by jabby** [comment]
@pascalleclercq What do you think about bintray ? https://bintray.com/ @paulvi use this service for nodeclipse. It's free for OSS distribution.

**Comment by paulvi** [comment]
> i uploaded the repo as a single zip here :
https://github.com/angelozerr/angularjs-eclipse/releases/tag/angularjs-eclipse-0.9.0

That is nice, 

Angular needs tern, so they should come together 
see https://github.com/angelozerr/tern.java/issues/271

> I have to do It manually, I'm looking for a way to do It automatically are release time.

> I think I have to look for another http hosting for the update sites.

> The ones that already exists is provided from a french provider : http://www.online.net/

Does it scale automatically to several locations?
If it is online in Europe, then locations like Asia-Pacific are be much slower.

> Not sure why you can't browse It from China.
I can browse, it was @maheshk172 who said he could not.

Does anybody has a suggestion for an alternative http hosting ? (for a limited budget)

First consider only free options:  read http://www.nodeclipse.org/nodeclipse/binaries/bintray/2014/05/09/Nodeclipse-on-Bintray.html

1. SourceForge http://sourceforge.net/ is very slow, some projects can't be even opened (guess they are phisically on different servers), the speed can be 0 to 6KB/s
2. GitHub http://github.com/ is quicker ~10KB/s, very rarely unavailable, but there is problem with big file. GitHub Flavored Markdown Viewer has 6MB file which download was almost always lost, Eclipse seems to be able to continue install, but it can't resume file download. (From very early GitHub have been saying that they are optimized for small files. And for 2-3 years they had their binary download service just closed)
3. Bintray https://bintray.com/ is 15-30KB/s, that is almost 3 times quicker 

That was my experience a year ago. Now Tern.java is included and total download is very slow (several minutes, often breaks) 

I use Bintray for p2 repo and SourceForge for zips (it is nice too see them all in one folder
http://sourceforge.net/projects/nodeclipse/files/update-site-archive/ )

**Comment by paulvi** [comment]
P.P.S. I am easy to add you to nodeclipse organization on Sourceforge, so you can upload zip. See also https://github.com/angelozerr/angularjs-eclipse/issues/36  "name" and #152

**Comment by maheshk172** [comment]
Guys, I am able to download and install now.  But I do not see anything in my preferences etc.  No specific errors as such. Please advise.

**Comment by pascalleclercq** [comment]
Ok, thanks @paulvi your feedbacks !

I will investigate Bintray for hosting p2 repo hosting, looks like the best suggested solution.

In the mean time I found this plugin :  https://github.com/jutzig/github-release-plugin/ which enable upload  of the zip file containing the p2 repo associated with the tag on github (just like I did manually).

**Comment by pascalleclercq** [comment]
Hi @paulvi 

I read : http://blog.bintray.com/2014/03/11/hosting-your-eclipse-update-site-p2-on-bintray-com/
but I'm not sure if you upload your p2 repo manually, do you ?

Would be quite cumbersome...

**Comment by jabby** [comment]
Hi @pascalleclercq 

Like I said [https://github.com/angelozerr/tern.java/issues/201#issuecomment-66593968](here), there is a script here to publish on bintray. https://github.com/vogellacompany/bintray-publish-p2-updatesite

@paulvi add some other useful links : 
* http://www.nodeclipse.org/nodeclipse/binaries/bintray/2014/05/09/Nodeclipse-on-Bintray.html
* https://github.com/golo-lang/gldt/issues/2

**Comment by pascalleclercq** [comment]
thanks @jabby for the tip.

I used https://github.com/vogellacompany/bintray-publish-p2-updatesite to deploy LATEST (-SNAPSOT)
version to :
https://dl.bintray.com/pascalleclercq/angularjs-eclipse
https://dl.bintray.com/pascalleclercq/tern.java
https://dl.bintray.com/pascalleclercq/jsbuild-eclipse
https://dl.bintray.com/pascalleclercq/eclipse-wtp-webresources
https://dl.bintray.com/pascalleclercq/eclipse-wtp-json

As usual every feedback is welcome !

**Comment by jabby** [comment]
@pascalleclercq I tried to use https://dl.bintray.com/pascalleclercq/angularjs-eclipse but I have the following message on bintray : "The requested path was not found."

When I tried to use it in Eclipse, there is an exception because Eclipse didn't find anything to install.

**Comment by pascalleclercq** [comment]
@jabby thanks for your feedback ! There were a typo in the job configuration. It is fixed now.

**Comment by paulvi** [comment]
well, i think it is too early to close issue until https://dl.bintray.com/pascalleclercq/* sites are tested with speed. But it can be other issue.
