### ISSUE TITLE
No repository found at...

### ISSUE THREAD

**Issue by rcw0086** [angelozerr/angularjs-eclipse#157]
When I try to install the AngularJS plugin in eclipse via Eclipse MarketPlace or dragging and dropping from https://marketplace.eclipse.org/content/angularjs-eclipse, I get the following response:

"No repository found at http://oss.opensagres.fr/angularjs-eclipse/0.10.0/."

**Comment by angelozerr** [comment]
Which version of Eclipse, do you use? I suggest you to use Eclipse JEE Mars.

**Comment by rcw0086** [comment]
I have Luna installed - in your experience, does Mars fix this issue? I only ask because it would be troublesome to upgrade

**Comment by angelozerr** [comment]
It should work. Perhaps it's a problem with the network?

**Comment by angelozerr** [comment]
Have you tried to install with Update Site?

**Comment by rcw0086** [comment]
I haven't - what's the URL for the update site?

Regards,
- rw

**Comment by angelozerr** [comment]
Same url http://oss.opensagres.fr/angularjs-eclipse/0.10.0/

**Comment by angelozerr** [comment]
@rcw0086 have you fixed your problem? Can I close this issue?

**Comment by rcw0086** [comment]
Yes, I figured out what was going on.  Thank you for corresponding with me
about this.

Regards,
- rw

**Comment by angelozerr** [comment]
Thanks @rcw0086 for your feedback. I close the issue.
