### ISSUE TITLE
Data binding issue

### ISSUE THREAD

**Issue by Vikasts** [angelozerr/angularjs-eclipse#160]
I installed angularjs plugin by following the link  :

https://github.com/angelozerr/angularjs-eclipse/wiki/Getting-Started

with eclipse Luna Version: Luna Service Release 1 (4.4.1)

and i have followed to create the angualr jsproject by follwoign the link :

http://blog.diniscruz.com/2014/02/using-angularjs-in-eclipse-part-1.html

i opened the The_basics.html file in browser enterd some value in textbox Name:
the value is not getting binded. I always get Hello {{yourName}}! 

I have tried reinstalling the plugin but nothing works.

**Comment by angelozerr** [comment]
> i opened the The_basics.html file in browser enterd some value in textbox Name:
the value is not getting binded. I always get Hello {{yourName}}!

It's not a problem with AngularJS Eclipse.

**Comment by Vikasts** [comment]
Thanks for your reply. 

Could please guide me what could be the possible problem in this case ?

**Comment by angelozerr** [comment]
I suggets you that you find an Angular forum to post your question if you rproblem is about using Angular in a browser.

**Comment by Vikasts** [comment]
well my problem is with the data binding the values not only with browser. 

In the The_basics.html file preview also the values are not get binded.

**Comment by angelozerr** [comment]
> In the The_basics.html file preview

AngularJS Eclipse doesn't provide preview (perhaps it's an other plgin which provides preview, but I think it is based on browser).

**Comment by Vikasts** [comment]
When i right click on The_Basics.html-->openwith i don't get an option "angularjs editor"  and in eclipse--preferences--Tern , i dont get modules option .. i just have Node.js

**Comment by angelozerr** [comment]
> When i right click on The_Basics.html-->openwith i don't get an option "angularjs editor" 

Yes it's normal. AngularJS Editor was removed because today it's possible to use classic WTP HTML Editor.

> and in eclipse--preferences--Tern , i dont get modules option .. i just have Node.js

For modules selection, you must open project properties (and not Window/Preferences). Please note that 1.0.0 was released today.

**Comment by Vikasts** [comment]
i tried to install the latest plugin 1.0.0 in eclipse luna, i got an error while installing the software as : 

'Installing Software' has encountered a problem. An error occured while collecting items to be installed. session contect was : (profile=epp.package.jee,phase=org.eclipse.equinox.internal.p2.engine.phases. Colelct, openrand=,action=). Unable to read repository at http://oss.opensagres.fr/angularjs-eclipse/1.0.0/plugins/ternjs_1.0.0.201508302102.jar. Read time out

**Comment by angelozerr** [comment]
> Read time out

I think it's because a lot of users triy to install it and this server is not quick (no money to have a quick server). Please retry it later.

**Comment by tpatel11** [comment]
I am also facing the issue similar to above mentioned. Every time I run simple index.html page, it only displays {{storecontroller.name}}. It is supposed to display value of product but something seems wrong with that. I am thinking to go away from using Eclipse for angularjs now.

**Comment by angelozerr** [comment]
> It is supposed to display value of product but something seems wrong with that.

AngularJS Eclipse doesn't provide Web Browser. Perhaps you are trying to open your HTML page with Eclipse Web Browser and you have a problem, but it's not related to AngularJS Eclipse.

>  but something seems wrong with that

The only thing that I see to improve AngularJS Eclipse is to validate Angular expression. I have created issue at https://github.com/angelozerr/angularjs-eclipse/issues/162

**Comment by Vikasts** [comment]
Its a browser issue. Open the HTML page in Google Chrome. It will work.

**Comment by pramodinis** [comment]
I have installed 

Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

I am facing this issue , please suggest me how to resolve this one.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/angularjs-eclipse/1.1.0/plugins/ternjs_1.1.0.201511082254.jar.
Premature end of Content-Length delimited message body (expected: 16753236; received: 821027

**Comment by angelozerr** [comment]
As @Vikasts suggested:

> Its a browser issue. Open the HTML page in Google Chrome. It will work.
