### ISSUE TITLE
Unsigned content

### ISSUE THREAD

**Issue by JeffInTampa** [angelozerr/angularjs-eclipse#161]
Angelo,
I started to install the plugin from the eclipse marketplace, but got the "unsigned content" warning. In my work environment this is a show-stopper. Will you be providing signed content at some point?

**Comment by angelozerr** [comment]
> "unsigned content" warning

It's just a warn, install should work.

I don't know how to avoid that.

**Comment by angelozerr** [comment]
@pascalleclercq have you an idea about that?

**Comment by jabby** [comment]
To avoid the warning you can sign all plugins. More information in following links : 
https://wiki.eclipse.org/JAR_Signing
https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_plugins.2FZIP_files.3F
https://nirmalsasidharan.wordpress.com/2010/09/04/signing_eclipse_plugins/

**Comment by JeffInTampa** [comment]
Hi Angelo,
For the time being I'll have to use the plugin only on one of my personal machines, not at work. I'll probably install the plugin tonight and start exploring features.
