### ISSUE TITLE
What about Angular2 Eclipse support?

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angularjs-eclipse#164]
I create this issue because more and more people tell me if AngularJS Eclipse supports Angular2. The answer is no-( 

But I have studied how we could provide this support. The first thing is that Angular2 samples that I have found are based on TypeScript. Here a sample at http://blog.thoughtram.io/angular/2015/03/27/building-a-zippy-component-in-angular-2.html

It's possible to write Angular2 with ES5 too http://blog.thoughtram.io/angular/2015/05/09/writing-angular-2-code-in-es5.html but it seems that the use of TypeScript is a better mean.

1) [HTML] Angular2 syntax

Angular2 provides new syntax for Angular expression. HTML editor must support it (syntax highlight, completion, validation, etc). For instance supports this syntax:

```html
<li *ng-for="#name of names">
```
See http://blog.thoughtram.io/angular/2015/08/11/angular-2-template-syntax-demystified-part-1.html for more infos.

2) [JavaScript] Angular2 with ES5

To support that we need to write a tern plugin for Angular2 like it exists for Angular 1.x

3) [JavaScript] Angular2 with TypeScript

tern doesn't support ES7 decorator and TypeScript. See issues https://github.com/marijnh/tern/issues/652 which provides a mean to support TypeScript with language service. tern.java could use the existing tern server but instead of using ternjs it will use TypeScript language service.

But the big problem will be for Highlight. Is JSDT will be OK to support TypeScript syntax for syntax coloration? @vrubezhny could you give us an answer?

An other solution, should be to use an Eclipse TypeScript plugins like:

 * https://github.com/palantir/eclipse-typescript
 * https://github.com/axmor/typecs

But my prefer mean is to use JSDT JavaScript Editor.

@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @fbricon @piotrtomiak @kaloyan-raev @paulvi @jabby any feedback are welcome!

**Comment by victor** [comment]
Sorry I did not respond before. I am a bit confused, I have no idea what you're talking about.

**Comment by angelozerr** [comment]
@victor grrrrrrrrrr I'm really sorry with my mistake (completion with github to retrieve name).

**Comment by paulvi** [comment]
I repeat myself again, we should be promoting and teaching how to write tern plugins.
And make tern visible to all users.

Otherwise it will be impossible for Angelo to update plugins for all JavaScript framework, and *test* them, because it is impossible for one person to use all the frameworks, libraries and modules.
There's no fun of doing that.

**Comment by angelozerr** [comment]
I close this issue. I have decided to give up Angular2 support with tern.java and support Angular2 with TypeScript with :

 * https://github.com/angelozerr/typescript.java
 * https://github.com/angelozerr/angular2-eclipse which will based on https://github.com/angelozerr/typescript.java

**Comment by paulvi** [comment]
Hooray!

**Comment by paulvi** [comment]
Is there alliance growing between Google and Microsoft?

**Comment by angelozerr** [comment]
@paulvi glad my idea please you. typescript.java starts working (completion, hyperlink, hover, validation). I'm working on preferences (choose node.js, choose typescript bundle). For advanced features like refactoring, search, outline, etc I will see that in later. I would like to intialize Angular2 Eclipse soon based on typescript.java. I'm very motivated because my integration of TypeScript inside Eclipse looks like VSCode which consumes tsserver too.

> Is there alliance growing between Google and Microsoft?

I think really. You can see current work of Microsoft guy which is working on Angular2 https://github.com/Microsoft/TypeScript/issues/6508 and you will see an ansewone demo with Angular2. I'm  very excited that this plugin will be available to integrate it inside Angular2 Eclipse
