### ISSUE TITLE
How to run Protractor Scripts in Eclipse 

### ISSUE THREAD

**Issue by Nikhil0538** [angelozerr/angularjs-eclipse#165]
I would like to run the protractor test with in the eclipse, instead of starting selenium server from command prompt. scripts should run as directly from the eclipse.
Is there a way to add selenium server to the eclipse?
Please let me know your comments on this.

**Comment by angelozerr** [comment]
@Nikhil0538 today I don't know how we could provide that but there is an interesting project at https://github.com/CodeSmell/AngularJumpstart

**Comment by angelozerr** [comment]
@Nikhil0538 I'm working on this feature. See https://github.com/angelozerr/angularjs-eclipse/issues/178 and https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor

**Comment by sagar021988** [comment]
Hello @angelozerr 
I am new to protractor and i have configured protractor on eclipse luna on windows 10 and while running the protractor test case via eclipse i am facing error as 👍 

module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\Users\Sagar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

Can you please help me in debugging the same with complete solution step by step as i need this urgently .

Thanks in advance for your co operation

**Comment by Gaurav08021989** [comment]
I am also facing the same problem
