### ISSUE TITLE
All translations shown with Warning "Undefined attribute value"

### ISSUE THREAD

**Issue by Rhobal** [angelozerr/angularjs-eclipse#166]
All my "translate" directives give an "Undefined attribute value" warning.  I load my translations from a UrlLoader from Java properties files, where I have more readable files and a better editor than with "angular translate" translations.

Can I turn off these warnings? Or even better, can I configure the Java properties file as source of the translations?

**Comment by angelozerr** [comment]
I don't know "translation" with Angular, you mean https://github.com/angular-translate/angular-translate ?

> Can I turn off these warnings?

With Eclipse Mars ou can set the name of the attribute to ignore. Go at  projet properties, Validation -> HTML Syntax, "ignore specified attributes name".

> Or even better, can I configure the Java properties file as source of the translations?

No, but is it a standard mean or a custom mean to support translate with Angular?

**Comment by Rhobal** [comment]
Yes, I am using angular translate with the URL you gave.

I just found out that angular translate overrides the HTML 5 attribute "translate" which only takes yes or no as attributes. So the warning is completely unrelated to angularjs-eclipse
