### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dave-lemen** [angelozerr/angularjs-eclipse#167]
When attempting to install from Eclipse Marketplace I get this error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Tern feature 1.0.0.201508302102 (tern-feature.feature.group 1.0.0.201508302102)
  Missing requirement: Tern - Server - Nodejs 1.0.0.201508302102 (tern.server.nodejs 1.0.0.201508302102) requires 'package org.apache.http.client 4.1.3' but it could not be found
  Cannot satisfy dependency:
    From: Tern feature 1.0.0.201508302102 (tern-feature.feature.group 1.0.0.201508302102)
    To: tern.eclipse.ide.core [1.0.0.201508302102]
  Cannot satisfy dependency:
    From: Tern - Eclipse - Core IDE 1.0.0.201508302102 (tern.eclipse.ide.core 1.0.0.201508302102)
    To: bundle tern.server.nodejs 0.0.0

I get the same error when attempting to install the "Tern Eclipse IDE" as well.

My setup
- Windows 8.   
- Eclipse Java EE IDE for Web Developers.
    Version: Indigo Service Release 2
    Build id: 20120216-1857
- tomcat 7.0
- Java JRE 1.8.0_60

**Comment by angelozerr** [comment]
Eclispe Indigo is so old. Please use Eclipse Mars.

**Comment by dave-lemen** [comment]
Using Mars seems to work. I was able to install successfully.  Thanks for the quick advice!
