### ISSUE TITLE
Where is stored associations/links?

### ISSUE THREAD

**Issue by Rorkal** [angelozerr/angularjs-eclipse#168]
Hi! 

It happens some times i loose my links between HTML controller and his module.
The goal is to use this on a project with many users and i want to share it between developers.
Knowing where links are stored will be very helpfull!

**Comment by angelozerr** [comment]
@Rorkal I'm sorry, I don't understand your problem? Could you give me a sample code which doesn't work?

**Comment by jabby** [comment]
@angelozerr I think that Alex wants to use the functionnality describe  [here](https://github.com/angelozerr/angularjs-eclipse/wiki/Angular-Explorer-View#html-template-linkunlink) and he needs to share this configuration with other developers on his project. 

So basically, if association is stored in a file in the project, Alex will be able to share the configuration with other developers  through a VCS like SVN or git.

**Comment by angelozerr** [comment]
Thanks @jabby, I understand more now:) Indeed, the link are stored in the metadata IFile, so we cannot share that. To share that we need a preferences file which hosts the whole links of the project. It requires that we need to observe move/delete file to update the links.

I think https://github.com/angelozerr/angularjs-eclipse/issues/102 should avoid using links at hand.

**Comment by Rorkal** [comment]
Thanks @jabby , that was exactly what I meant!
Indeed @angelozerr , I think it will be hard to share links between developers. 
Maybe I will just try turn off error about linking HTML to JS and developers will handle that when needed.
Thanks!

**Comment by angelozerr** [comment]
@Rorkal as I said you, I must implement #102 to fix your issue.

**Comment by Rorkal** [comment]
Yes I understand. It will be great when implemented. :)
