### ISSUE TITLE
Issue downloading from marketplace

### ISSUE THREAD

**Issue by yuxblank** [angelozerr/angularjs-eclipse#172]
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/angularjs-eclipse/1.1.0/plugins/ternjs_1.1.0.201511082254.jar.
Premature end of Content-Length delimited message body (expected: 16753236; received: 831485

**Comment by angelozerr** [comment]
@yuxblank your repository is not very quick. I know that some people have a problem to download it.

Please try with update site https://github.com/angelozerr/angularjs-eclipse/wiki/Installation-Update-Site or https://github.com/angelozerr/angularjs-eclipse/releases

**Comment by yuxblank** [comment]
Thank you. Downloading the jar manually solved the issue.
Nice work keep it up!
