### ISSUE TITLE
Ionic tag <ion-footer-bar>

### ISSUE THREAD

**Issue by HaiboLee** [angelozerr/angularjs-eclipse#174]
I hava a issues, I use the ionic, the directive tag `<ion-footer-bar>` and `<ion-header-bar>` can't find.other tag is ok.

![unnamed](https://cloud.githubusercontent.com/assets/1932211/11866971/91291eb0-a4ae-11e5-9804-3ef2b51d3df3.png)

When use you AngularJS plugin. can you tell me why? Thank you very much.

**Comment by HaiboLee** [comment]
the tag<ion-foot-bar> and <ion-harder-bar>

**Comment by HaiboLee** [comment]
ion-footer-bar  and ion-header-bar

**Comment by angelozerr** [comment]
@HaiboLee it's a bug of the tern angular plugin. It will study why there is this problem.

**Comment by HaiboLee** [comment]
thanks

**Comment by angelozerr** [comment]
@HaiboLee please install 1.2.0-SNAPSHOT (see https://github.com/angelozerr/angularjs-eclipse/wiki/Installation-Update-Site), your problem should be fixed and more now you will have "Open Angular Element" feature See https://github.com/angelozerr/angularjs-eclipse/issues/175#issuecomment-166833776 for more information.

**Comment by HaiboLee** [comment]
thanks,it's good

**Comment by angelozerr** [comment]
Ok cool, I close this issue.
