### ISSUE TITLE
Provide Quick Outline to search modules, controllers, etc

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angularjs-eclipse#175]
It should be cool if we could have a quick outline (like Ctrl+O for JavaScript, Java) to search and go to the definition for angular modules, controllers, etc

@mickaelistria @piotrtomiak @paulvi @dgolovin @vrubezhny @maxandersen @jabby  @fbricon what do you think about this idea?

**Comment by jabby** [comment]
It's a good idea. In fact, I will be really happy to have this feature. I think that quick outline is more useful than the outline :-)

**Comment by angelozerr** [comment]
Ok, I have commited m work for this issue. I have called that "Open Angular Element". It is available with "Ctrl+Sift+Z" and it opens a window popup like "Open Resource" or "Open Type". This window display the whole modules, controllers, etc of the all Angular project (like "Open Type" for Java & JavaScript)

Here a demo with ionic project:

![test](https://cloud.githubusercontent.com/assets/1932211/11973237/c38a3d6e-a957-11e5-9666-d7bf6ac99a91.gif)

@mickaelistria @piotrtomiak @paulvi @dgolovin @vrubezhny @maxandersen @jabby @fbricon any feedback are welcome! 

 * is Ctrl+Shift+Z is ok?, 
 * is searching for the angular modules coming from the all angular project of the workspace is OK?,  * do you need some other information like display file in the status?)

@piotrtomiak there is a bug the first time that "Open ANgular Element" is opened with project which have several files (like ionic project) : the first time, the modules, etc doesn't appears in teh dialog because sync of files is not finished. Have you an idea how we could fix that? Thanks!

**Comment by angelozerr** [comment]
@piotrtomiak when you will have time, could you help me to know when sync of files is finished?

**Comment by maxandersen** [comment]
ctrl+shift+Z is redo afaik so that is not a good binding to use imo.

**Comment by angelozerr** [comment]
> ctrl+shift+Z is redo afaik so that is not a good binding to use imo.

Argh -( Have you a suggestion? thanks @maxandersen for your feedback!

**Comment by mickaelistria** [comment]
Ctrl+Shift+A seems to be free to use, and the "A" will easily be reminded as "Angular".

**Comment by angelozerr** [comment]
> Ctrl+Shift+A seems to be free to use, and the "A" will easily be reminded as "Angular".

Yes it was my first idea, but in my case when I do Ctrl+Shift+A , it opens "Open Plug-In Artifact"

**Comment by mickaelistria** [comment]
oh right, I missed the line with this shortcut... What about Ctrl+Shift+Alt+A ?

**Comment by angelozerr** [comment]
> oh right, I missed the line with this shortcut... What about Ctrl+Shift+Alt+A ?

Is it not complex to do Ctrl+Shift+Alt+A? If other people like this, I will do that.

**Comment by jabby** [comment]
@mickaelistria @angelozerr I think Ctrl+Shift+Alt+A is really too complicated.
In fact, I think that more than 3 keys is complicated for users.

**Comment by mickaelistria** [comment]
@jabby So your suggestion is...? ;)

**Comment by jabby** [comment]
I don't know. It's not really helpful, I know. 
* Alt + Shift + A : already use for "Toggle Block Selection"
* Ctrl + Shift + A : already use for "Open Plug-In Artifact"
* Ctrl + Alt + A : maybe some problem on Windows because Ctrl+Alt is same as Alt Gr.
* Ctrl + Shift + Alt + A : a little bit complicated

**Comment by piotrtomiak** [comment]
> @piotrtomiak when you will have time, could you help me to know when sync of files is finished?
IDETernFileUploader is responsible for uploading files. You can get to it with ITernServer.getFileSynchronizer().getFileUploader() . The join method should work, just put a long timeout.
