### ISSUE TITLE
Display modules, controllers, in a GEF diagram editor

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angularjs-eclipse#176]
It should be cool if we could display modules, controllers, in a GEF diagram editor

@mickaelistria @piotrtomiak @paulvi @dgolovin @vrubezhny @maxandersen @jabby  @fbricon what do you think about this idea?

**Comment by mickaelistria** [comment]
How would user take advantage of such an editor?
It wouldn't be a trivial thing to implement, so I believe you should make sure there are very common and useful user-stories for that before getting started on such a development.

**Comment by angelozerr** [comment]
> How would user take advantage of such an editor?

My idea is to show you an overview of your Angular application: modules and their dependencies. When you have a lot of modules, etc it can be hard to understand yoru application.

> It wouldn't be a trivial thing to implement, so I believe you should make sure there are very common and useful user-stories for that before getting started on such a development.

I agree with you. I had this idea, because I'm refactoring the tern angular plugin to refresh angular explorer automaticly (with WebSocket). So I will have a clean model and more I could send events with WebSocket to tell that a module is added, removed. So for GEF editor it's a features that it is required.

But if you think it's not trivial, I will not implemented it, I would like just to know your opinion.

**Comment by jabby** [comment]
What it the real value for user. Personnaly, I don't need a graph for my angularjs applications. If I need one, I will use this chrome plugin : [AngularJS Graph](https://chrome.google.com/webstore/detail/angularjs-graph/gghbihjmlhobaiedlbhcaellinkmlogj)

**Comment by angelozerr** [comment]
> I will use this chrome plugin : AngularJS Graph

Wow very impressive! Ok @mickaelistria @jabby this idea about GEF editor is a toy, I close this issue. Thanks for your feedback!
