### ISSUE TITLE
Cannot autocomplete variable name

### ISSUE THREAD

**Issue by nicola883** [angelozerr/angularjs-eclipse#179]
I have fresh installed Eclipse Mars PDT and Angularjs plugin.
All looks working, just I cannot see the auto complete suggestion of the name of the variables in the contest.
I.e. if I assign
var foo;
I'd like to see the suggest when I type
fo
I have enabled all in Content assist in javascript and tern.
Maybe this is an issue of tern, so I'm sorry if I'm asking you help, but I cannot find any solution.

Many thanks.

**Comment by angelozerr** [comment]
@nicola883 I don't understand your issue? 

```javascript
var foo;
fo // here Ctrl+Space should show foo
```

No? But perhaps you would like to have have completion which open without Ctrl+Space? If it that I'm not sure that it's possible?

**Comment by nicola883** [comment]
Thanks to your suggest I thought that the problem could be with my linux box configuration. And it was: the Ctrl+space combination was associated with an other application. Disabling this now it works!

I'd like to have completation without press any keys, like the PDT, php prospective does. But it's not so important like to have in one way ;) 

Many thanks!

**Comment by angelozerr** [comment]
> I'd like to have completation without press any keys

Perhaps JSDT provides this feature, I don't know?

I close this issue
