### ISSUE TITLE
unable to add plugin to eclipse neon, mars

### ISSUE THREAD

**Issue by vuthunori** [angelozerr/angularjs-eclipse#184]

**Comment by jabby** [comment]
Hello @vuthunori I use this plugin in Mars.1 since the release of Mars.1. So you can add this plugin without problem.

For Neon version of Eclipse, I just tried with the M4 and I have no problem to install the plugin. 

What is your problem ?

**Comment by angelozerr** [comment]
@vuthunori could you explain more what is your problem?

**Comment by angelozerr** [comment]
None answer I close this issue. I think it was the same problem than https://github.com/angelozerr/angularjs-eclipse/issues/185
