### ISSUE TITLE
This plugin is not compatible with eclipse neon

### ISSUE THREAD

**Issue by khushwinder** [angelozerr/angularjs-eclipse#185]
This plugin is not compatible with eclipse neon, will it be upgraded?

**Comment by angelozerr** [comment]
Is it the same issue than https://github.com/angelozerr/angularjs-eclipse/issues/184 ?

What do you mean with "not compatible"? Which problem do you have?

**Comment by khushwinder** [comment]
I am getting err while installation that this plugin is not compatible with
eclipse neon version.

**Comment by angelozerr** [comment]
Ok I will try with neon. AngularJS Eclipse will be compatible with neon, because it will use for instance new WTP custom validator to improve a lot validation of HTML angular elements/attributes https://github.com/angelozerr/angularjs-eclipse/issues/183

**Comment by khushwinder** [comment]
Thanks for trying .

**Comment by angelozerr** [comment]
DO you use update site or market place? It seems that with update site it can resolve dependencies. Could you add a screenshot with your error please and tell me which OS you are using.

**Comment by khushwinder** [comment]
I used marketplace.

**Comment by angelozerr** [comment]
Please retry with marketplace or use update site.

**Comment by khushwinder** [comment]
its great working now , appreciate quick fix.
