### ISSUE TITLE
Canot install SNAPTSHOT version in Mars 1

### ISSUE THREAD

**Issue by calinmarina** [angelozerr/angularjs-eclipse#186]
Version: Mars.1 Release (4.5.1)

I get this:
![image](https://cloud.githubusercontent.com/assets/1877148/13321980/92af5d48-dbd2-11e5-976f-decb19f8871e.png)

> An error occurred while collecting items to be installed
> session context was:(profile=_Users_calin_tools_eclipse-java-mars_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> Artifact not found: http://oss.opensagres.fr/angularjs-eclipse/1.2.0-SNAPSHOT/plugins/tern.eclipse.ide.server.nodejs.embed.macosx.cocoa.x86_64_1.2.0.201602050912.jar.
> http://oss.opensagres.fr/angularjs-eclipse/1.2.0-SNAPSHOT/plugins/tern.eclipse.ide.server.nodejs.embed.macosx.cocoa.x86_64_1.2.0.201602050912.jar

**Comment by angelozerr** [comment]
Could you retry please. We had a problem with cloudbees.

**Comment by calinmarina** [comment]
worked perfect now... thank you.
