### ISSUE TITLE
Cannot complete the install because one or more required items could not be found

### ISSUE THREAD

**Issue by jsoomro** [angelozerr/angularjs-eclipse#190]
Cannot complete the install because one or more required items could not be found.
  Software being installed: AngularJS support for PHP (PDT) 1.1.0.201511091212 (angularjs-eclipse-php-feature.feature.group 1.1.0.201511091212)
  Missing requirement: Tern - Server - Nodejs 1.1.0.201511082254 (tern.server.nodejs 1.1.0.201511082254) requires 'package org.apache.http.client 4.1.3' but it could not be found
  Cannot satisfy dependency:
    From: AngularJS support for PHP (PDT) 1.1.0.201511091212 (angularjs-eclipse-php-feature.feature.group 1.1.0.201511091212)
    To: org.eclipse.angularjs.php.core [1.1.0.201511091212]
  Cannot satisfy dependency:
    From: Eclipse AngularJS PHP - Core 1.1.0.201511091212 (org.eclipse.angularjs.php.core 1.1.0.201511091212)
    To: bundle tern.eclipse.ide.core 0.0.0
  Cannot satisfy dependency:
    From: Tern - Eclipse - Core IDE 1.1.0.201511082254 (tern.eclipse.ide.core 1.1.0.201511082254)
    To: bundle tern.server.nodejs 0.0.0

**Comment by angelozerr** [comment]
Please install AngularJS Eclipse with "Eclipse JEE" Mars distribution

**Comment by jsoomro** [comment]
Ok, so it would not work with eclipse juno,

thanks
