### ISSUE TITLE
Unable to download ternjs_1.1.0.201511082254.jar

### ISSUE THREAD

**Issue by isprabakar** [angelozerr/angularjs-eclipse#192]
I tried to download/install the angular js plugin for eclipse (Luna) multiple times, but in vain. Every time, the download failed when downloading the ternjs.jar file:
"An error occurred while collecting items to be installed session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/tern.repository/1.1.0/plugins/ternjs_1.1.0.201511082254.jar.
Read timed out"
I am using Eclipse IDE for Java Developers
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

I also tried to download the jar file directly from browser, and again it failed stating "network error" (after around 700K of download). 
What could be the problem...? Is anyone else facing similar issue/solved it..?

**Comment by angelozerr** [comment]
I don't know yiou have tfis problem but in my case it works. I suggest you that you try to install 1.2.0-SNAPSHOT.

**Comment by isprabakar** [comment]
Thank you for the quick response. Tried the 1.2.0-SNAPSHOT and still facing the same issue. :-(
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/angularjs-eclipse/1.2.0-SNAPSHOT/plugins/ternjs_1.2.0.201603071119.jar.
Connection reset

**Comment by angelozerr** [comment]
I think your network is slow, try to download local update site at https://github.com/angelozerr/angularjs-eclipse/releases

**Comment by isprabakar** [comment]
Great! I downloaded the zip version from github and installed the angular js plugin from the same. I was able to download the zip fully (36 MB) and successfully install it too. Thank you for the help!

**Comment by ripplejb** [comment]
I had same issue. This is what I did...

I downloaded the file and copied the file in Plugin folder. Restart installation of the plugin and it worked.

**Comment by mailtoab** [comment]
hello @angelozerr
I am getting the following error 
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/angular2-eclipse/1.2.0-SNAPSHOT/plugins/ts.repository_1.2.0.201703072021.jar.
Premature end of Content-Length delimited message body

while installing Angular2 IDE plugin on Neon Eclipse from the following HTTP directory
http://oss.opensagres.fr/angular2-eclipse/1.2.0-SNAPSHOT/

Please help.
