### ISSUE TITLE
Auto complete not working on Eclipse Mars 4.5.2

### ISSUE THREAD

**Issue by mihaibuba** [angelozerr/angularjs-eclipse#193]
Since I did nothing really special, I am assuming it is due to the version of Eclipse I am using, which is 4.5.2, (but this is just a strong guess!); anyway here it is:

**# Steps to reproduce:**

- [ ] Install version 1.1.0 of the plugin from the marketplace, with all additional features (both required and optional)
- [ ] Configured tarn to run both as native (v 4.4.2), as well as embedded
- [ ] Imported angular-seed from git;
- [ ] Configure -> Convert to AngularJS
- [ ] [Optional] Added all folders as Script Paths in: Project properties -> Tern -> Script Paths.
- [ ] Opened up view1.js and typed "angular."
- [ ] Created a new _index.html_ file in _view1_ folder and typed: `<!DOCTYPE html>
<html ng-`

**# Expected:**
A pop-up with the auto complete options.

**# Actual:**
Nothing happening.

**# Environment:**
eclipse-jee-4.5.2-mars-2-SR2-win32-x86_64

**# Tern console output:**
Tern response#definition with 53ms: 
Project dir: D:\My Documents\Software Development\git\angular-seed
Nodejs Commnand: "D:\My Documents\Software Development\eclipse-jee-4.5.2-mars-2-SR2-win32-x86_64\plugins\tern.eclipse.ide.server.nodejs.embed.win32.win32.x86_64_1.1.0.201511082254\node-v0.10.22-win32-x86_64\node.exe" "D:\My Documents\Software Development\eclipse-jee-4.5.2-mars-2-SR2-win32-x86_64\plugins\ternjs_1.1.0.201511082254\node_modules\tern\bin\tern" --no-port-file --disable-loading-local
Tern response#definition with 14ms: 
-----------------------------------
{"origin":"app/view1/view1.js","start":37,"end":50,"file":"app/view1/view1.js","contextOffset":37,"context":"'use strict';\nangular\nangular.module('myApp.view1'"}

{"query":{"type":"definition","file":"app/view1/view1.js","end":44},"files":[{"name":"app/view1/view1.js","text":"'use strict';\nangular\nangular.module('myApp.view1', ['ngRoute'])\n\n.config(['$routeProvider', function($routeProvider) {\n  $routeProvider.when('/view1', {\n    templateUrl: 'view1/view1.html',\n    controller: 'View1Ctrl'\n  });\n}])\n\n.controller('View1Ctrl', [function() {\n\n}]);","type":"full"}]}
Tern request#definition: 
-----------------------------------
-----------------------------------
{"origin":"app/view1/view1.js","start":37,"end":50,"file":"app/view1/view1.js","contextOffset":37,"context":"'use strict';\nangular\nangular.module('myApp.view1'"}

{"query":{"type":"definition","file":"app/view1/view1.js","end":44},"files":[{"name":"app/view1/view1.js","text":"'use strict';\nangular\nangular.module('myApp.view1', ['ngRoute'])\n\n.config(['$routeProvider', function($routeProvider) {\n  $routeProvider.when('/view1', {\n    templateUrl: 'view1/view1.html',\n    controller: 'View1Ctrl'\n  });\n}])\n\n.controller('View1Ctrl', [function() {\n\n}]);","type":"full"}]}
Server started at 65395 in 291ms
Tern request#definition: 
.tern-project: {
  "ecmaVersion": 5,
  "ide": {
    "scriptPaths": [
      {
        "type": "PROJECT",
        "path": "helloconsumeronline"
      }
    ]
  },
  "plugins": {
    "guess-types": {
      
    },
    "outline": {
      
    },
    "angular": {
      
    }
  },
  "libs": [
    "ecma5",
    "browser"
  ]
}
-----------------------------------
Tern request#: 
{"files":[{"name":"app/view1/view1.js","text":"","type":"full"}]}

Tern response# with 23ms: 
{}
-----------------------------------
-----------------------------------
Tern request#type: 
{"query":{"type":"type","file":"app/view1/view1.js","end":93,"docs":true,"urls":true,"types":true},"files":[{"name":"app/view1/view1.js","text":"'use strict';\nangular\nangular.module('myApp.view1', ['ngRoute'])\n\n.config(['$routeProvider', function($routeProvider) {\n  $routeProvider.when('/view1', {\n    templateUrl: 'view1/view1.html',\n    controller: 'View1Ctrl'\n  });\n}])\n\n.controller('View1Ctrl', [function() {\n\n}]);","type":"full"}]}

Tern response#type with 20ms: 
{"type":"fn($routeProvider: provider.$routeProvider)","origin":"app/view1/view1.js"}
-----------------------------------
-----------------------------------
Tern request#: 
{"files":[{"name":"target/classes/META-INF/MANIFEST.MF","text":"","type":"full"},{"name":"target/classes/META-INF/maven/angular-seed/angular-seed/pom.properties","text":"","type":"full"},{"name":"target/classes/META-INF/maven/angular-seed/angular-seed/pom.xml","text":"","type":"full"}]}

Tern response# with 20ms: 
{}
-----------------------------------
Nodejs Commnand: "D:\My Documents\Software Development\eclipse-jee-4.5.2-mars-2-SR2-win32-x86_64\plugins\tern.eclipse.ide.server.nodejs.embed.win32.win32.x86_64_1.1.0.201511082254\node-v0.10.22-win32-x86_64\node.exe" "D:\My Documents\Software Development\eclipse-jee-4.5.2-mars-2-SR2-win32-x86_64\plugins\ternjs_1.1.0.201511082254\node_modules\tern\bin\tern" --no-port-file --disable-loading-local
Project dir: D:\My Documents\Software Development\git\angular-seed
.tern-project: {
  "ecmaVersion": 5,
  "ide": {
    "scriptPaths": [
      {
        "type": "FOLDER",
        "path": "app"
      },
      {
        "type": "FOLDER",
        "path": "app/components"
      },
      {
        "type": "FOLDER",
        "path": "app/components/version"
      },
      {
        "type": "FOLDER",
        "path": "app/view1"
      },
      {
        "type": "FOLDER",
        "path": "app/view2"
      }
    ]
  },
  "plugins": {
    "guess-types": {
      
    },
    "outline": {
      
    },
    "angular": {
      
    }
  },
  "libs": [
    "ecma5",
    "browser"
  ]
}
-----------------------------------
Tern request#: 
Server started at 50819 in 937ms
{"files":[{"name":"app/app.js","text":"'use strict';\n\n// Declare app level module which depends on views, and components\nangular.module('myApp', [\n  'ngRoute',\n  'myApp.view1',\n  'myApp.view2',\n  'myApp.version'\n]).\nconfig(['$routeProvider', function($routeProvider) {\n  $routeProvider.otherwise({redirectTo: '/view1'});\n}]);\n","type":"full"},{"name":"app/components/version/interpolate-filter.js","text":"'use strict';\n\nangular.module('myApp.version.interpolate-filter', [])\n\n.filter('interpolate', ['version', function(version) {\n  return function(text) {\n    return String(text).replace(/\\%VERSION\\%/mg, version);\n  };\n}]);\n","type":"full"},{"name":"app/components/version/interpolate-filter_test.js","text":"'use strict';\n\ndescribe('myApp.version module', function() {\n  beforeEach(module('myApp.version'));\n\n  describe('interpolate filter', function() {\n    beforeEach(module(function($provide) {\n      $provide.value('version', 'TEST_VER');\n    }));\n\n    it('should replace VERSION', inject(function(interpolateFilter) {\n      expect(interpolateFilter('before %VERSION% after')).toEqual('before TEST_VER after');\n    }));\n  });\n});\n","type":"full"},{"name":"app/components/version/version-directive.js","text":"'use strict';\n\nangular.module('myApp.version.version-directive', [])\n\n.directive('appVersion', ['version', function(version) {\n  return function(scope, elm, attrs) {\n    elm.text(version);\n  };\n}]);\n","type":"full"},{"name":"app/components/version/version-directive_test.js","text":"'use strict';\n\ndescribe('myApp.version module', function() {\n  beforeEach(module('myApp.version'));\n\n  describe('app-version directive', function() {\n    it('should print current version', function() {\n      module(function($provide) {\n        $provide.value('version', 'TEST_VER');\n      });\n      inject(function($compile, $rootScope) {\n        var element = $compile('<span app-version></span>')($rootScope);\n        expect(element.text()).toEqual('TEST_VER');\n      });\n    });\n  });\n});\n","type":"full"},{"name":"app/components/version/version.js","text":"'use strict';\n\nangular.module('myApp.version', [\n  'myApp.version.interpolate-filter',\n  'myApp.version.version-directive'\n])\n\n.value('version', '0.1');\n","type":"full"},{"name":"app/components/version/version_test.js","text":"'use strict';\n\ndescribe('myApp.version module', function() {\n  beforeEach(module('myApp.version'));\n\n  describe('version service', function() {\n    it('should return current version', inject(function(version) {\n      expect(version).toEqual('0.1');\n    }));\n  });\n});\n","type":"full"},{"name":"app/view1/view1.js","text":"'use strict';\nangular\nangular.module('myApp.view1', ['ngRoute'])\n\n.config(['$routeProvider', function($routeProvider) {\n  $routeProvider.when('/view1', {\n    templateUrl: 'view1/view1.html',\n    controller: 'View1Ctrl'\n  });\n}])\n\n.controller('View1Ctrl', [function() {\n\n}]);","type":"full"},{"name":"app/view1/view1_test.js","text":"'use strict';\n\ndescribe('myApp.view1 module', function() {\n\n  beforeEach(module('myApp.view1'));\n\n  describe('view1 controller', function(){\n\n    it('should ....', inject(function($controller) {\n      //spec body\n      var view1Ctrl = $controller('View1Ctrl');\n      expect(view1Ctrl).toBeDefined();\n    }));\n\n  });\n});","type":"full"},{"name":"app/view2/view2.js","text":"'use strict';\n\nangular.module('myApp.view2', ['ngRoute'])\n\n.config(['$routeProvider', function($routeProvider) {\n  $routeProvider.when('/view2', {\n    templateUrl: 'view2/view2.html',\n    controller: 'View2Ctrl'\n  });\n}])\n\n.controller('View2Ctrl', [function() {\n\n}]);","type":"full"},{"name":"app/view2/view2_test.js","text":"'use strict';\n\ndescribe('myApp.view2 module', function() {\n\n  beforeEach(module('myApp.view2'));\n\n  describe('view2 controller', function(){\n\n    it('should ....', inject(function($controller) {\n      //spec body\n      var view2Ctrl = $controller('View2Ctrl');\n      expect(view2Ctrl).toBeDefined();\n    }));\n\n  });\n});","type":"full"}]}

{}
-----------------------------------
Tern response# with 45ms:

**Comment by angelozerr** [comment]
I have tested with Eclipse Mars 4.5.2 completion for  `<!DOCTYPE html>
<html ng-` and it works well? I suggest you try to install 1.2.0-SNAPSHOT with update site https://github.com/angelozerr/angularjs-eclipse/wiki/Installation-Update-Site

**Comment by mihaibuba** [comment]
I have tried the following:
- Uninstall version 1.1.0 + restart
- Install version 1.2.0-SNAPSHOT (checked on original project; not working)
- Created a separate workspace in Eclipse
- Imported angularjs-seed project in a new folder 
- Configure -> Convert to AngularJS project (checked; not working)
- Project properties -> Tern -> Script paths -> added all folders (checked; not working)
- Changed to both NodeJS version (native/embedded) (checked; not working)
- Restarted the machine  (checked; not working)

OK, it might just be my machine, but I can't figure out what, I have attached a screenshot of the installed plugins in eclipse, both with and without this plugin but I don't have anything fancy.

![eclipse installation details after uninstall](https://cloud.githubusercontent.com/assets/18402330/14438175/b8461062-fff2-11e5-8e78-4a8a61a73e2d.JPG)

![eclipse installation details](https://cloud.githubusercontent.com/assets/18402330/14438013/fbcb097e-fff1-11e5-97d7-ce4b2b2b5924.JPG)

**Comment by angelozerr** [comment]
I'm a little lost -( I suggest you that you share your project with github. It works for me?

**Comment by mihaibuba** [comment]
Well, you can just take a gun and shoot me :( When all the fancy stuff works, check that the switch is flipped, before you start taking apart the whole machine...
I didn't have content assist activated in Eclipse for JavaScript. So I did activate that, and also set the Editor to activate content assist when - is inserted in HTML files. 
![html activated](https://cloud.githubusercontent.com/assets/18402330/14444177/07debe98-0012-11e6-84e2-040d7cded09e.JPG)
![javascript activated](https://cloud.githubusercontent.com/assets/18402330/14444176/07dea1b0-0012-11e6-9738-e5b395fdf447.JPG)

**Comment by angelozerr** [comment]
Ok your problem was with "Auto activation", but you can open completion with Ctrl+Space.
