### ISSUE TITLE
Angular Install Error on Myeclipse

### ISSUE THREAD

**Issue by vt00341139** [angelozerr/angularjs-eclipse#195]
Logs says
Cannot complete the install because one or more required items could not be found.
  Software being installed: Tern server node.js feature 1.1.0.201511082254 (tern-server-nodejs-feature.feature.group 1.1.0.201511082254)
  Missing requirement: Tern - Server - Nodejs 1.1.0.201511082254 (tern.server.nodejs 1.1.0.201511082254) requires 'package org.apache.http 4.1.4' but it could not be found
  Cannot satisfy dependency:
    From: Tern server node.js feature 1.1.0.201511082254 (tern-server-nodejs-feature.feature.group 1.1.0.201511082254)
    To: tern.server.nodejs [1.1.0.201511082254]

**Comment by angelozerr** [comment]
Please use Eclipse Mars.

**Comment by vt00341139** [comment]
Fixed that issue as I downloaded eclipse mars earlier i was using myeclipse .Thanks for help

**Comment by angelozerr** [comment]
@piotrtomiak it's a strange problem, no?

**Comment by piotrtomiak** [comment]
@vt00341139 MyEclipse 2015 or 2016 ships with the latest Angular, so you should not need to install it additionally. Could you please provide more details on what kind of setup you have used?

**Comment by vt00341139** [comment]
I was using an old version of MyEclipse 2012

**Comment by piotrtomiak** [comment]
Ok, in this case I would advise you to migrate to the newer version, your license will still work with it. 2016 is based on Mars, whereas 2015 is based on Luna.

**Comment by vt00341139** [comment]
Ok thanks for the advice will do it definitely
