### ISSUE TITLE
Spring MVC backend Angular frontend

### ISSUE THREAD

**Issue by husnutapan** [angelozerr/angularjs-eclipse#198]
Hello friends I am working angularjs and backend section is Spring mvc.I am using eclipse IDE but angular's code not working on eclipse how can I entegred on that?

**Comment by angelozerr** [comment]
> but angular's code not working on eclipse how can I entegred on that?

Please give more information than "not working". Which problem do you have, completion, validation? I suggets you that you shar eyour project and tell me which problem you have.
