### ISSUE TITLE
Can't install tern.java 1.2.0 in Eclipse Java EE IDE 4.5.2

### ISSUE THREAD

**Issue by hkapur68** [angelozerr/angularjs-eclipse#204]
When I try to install tern.java 1.2.0 for Eclipse Java EE IDE 4.5.2 for Java developers, the installation starts but then stops just one quarter of the way through with an error whose details are as follows:

An error occurred while collecting items to be installed session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=). Unable to read repository at http://oss.opensagres.fr/tern.repository/1.2.0/plugins/ternjs_1.2.0.201606160856.jar.
Connection reset

The same error occurs even for other earlier versions of tern.java

**Comment by angelozerr** [comment]
It's because our server which host tern.java can be slow. You can download update site at hand at https://github.com/angelozerr/angularjs-eclipse/releases

**Comment by hkapur68** [comment]
How do I install it in Eclipse using this url: https://github.com/angelozerr/angularjs-eclipse/releases

**Comment by angelozerr** [comment]
It's a local update site. You use it like update site url  http://oss.opensagres.fr/tern.repository/1.2.0/ except you select the folder of the downloaded update site which is zipped. See http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-127.htm

**Comment by DivyaGN** [comment]
i don't see tern in the preference after installing in the Global Preferences.

i have installed tern tooling , ternserver nodejs feature,tern tooling,

and on preference ->Angular->protractor it says current display page contains invalid values

**Comment by DivyaGN** [comment]
I have also installed "Debugger support for Weclipse" amd nodeeclipse still it says "not installed " in run/debug protractor with.

**Comment by angelozerr** [comment]
>  have also installed "Debugger support for Weclipse" 

You need to install Webclipse plugin. See https://github.com/angelozerr/tern.java/wiki/Debugging-Tern.js-on-Node.js

**Comment by lizard1990** [comment]
good
