### ISSUE TITLE
AngularJS Eclipse 1.3 will work only with Eclipse Neon?

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angularjs-eclipse#206]
@piotrtomiak @vrubezhny @kaloyan-raev @alexeykazakov @dgolovin @mickaelistria I would like to use Neon WTP Custom HTML Editor to fix for instance https://github.com/angelozerr/angularjs-eclipse/issues/121 :
and I could remove my uggly WTP Validator to ignore errors for ng attributes, elements.

Are you agree with AngularJS Eclipse 1.3 will work only with Eclipse Neon?

**Comment by kaloyan-raev** [comment]
+1

Please, set a version constraint on the dependency, so AngularJS Eclipse 1.3 cannot install on Eclipse Mars and older.

**Comment by vrubezhny** [comment]
+1 

And +1 for version constraint adding.

**Comment by piotrtomiak** [comment]
+1

Sounds like a good idea.

**Comment by angelozerr** [comment]
Many thanks guys for your answer!

I have removed my `HTML Angular Syntax Validator` and replace it with HTML WTP custom validator, it's really clean, that's cool.

The custom validator :

 * ignore error for ng- (ng-app and custom directive) for attribute and element.
 * mark error when module (with ng-app), controller (ng-controller) is not found.

If you find bugs, please create issues. Thanks. I close this issue.
