### ISSUE TITLE
Cannot find node install path node-native Do you want to update Protractor preferences?

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angularjs-eclipse#207]
See http://stackoverflow.com/questions/38249062/eclipse-unable-to-find-install-path-node-native

**Comment by sujithsris** [comment]
Hi all
I am trying to setup protractor in eclipse IDE and  I have installed the bellow things so far...
npm version 3.10.10
protractor version 5.1.1
windows 10 pro 
Eclipse Neon (4.6.0)
AngularJS Eclipse 1.2.0
When iam trying to execute i getting error
 Error while launching client file
Cannot find node install path node-native
![image](https://cloud.githubusercontent.com/assets/28299386/25617754/74ab8f0e-2f61-11e7-9759-db1514f54ed2.png)
Please help me to sort out this @angelozerr

**Comment by yeikel** [comment]
Did you fix it?

**Comment by ZoeThivet** [comment]
Same error! Drives me kwayyyyzeeeeee

**Comment by chandra1653** [comment]
Hi ,
Did you fix the issue , I am also facing the same at my end

**Comment by srikrishna173** [comment]
Hi,
Even I am facing the same issue. Can anyone please help me .
Using 
1) npm version :- 3.10.10
2) Node version :- 6.11.3
3) Protractor Version. ;- 5.1.2
4) Eclipse Neon 2 
Selenium server is up and running.

Config Code :-
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js']
};
 Spec Code :- 
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
  });
});

The same script working fine in cmd but not in eclipse.

![image](https://user-images.githubusercontent.com/29059951/30741946-9dc37780-9fb4-11e7-8ed4-7cced05d30d5.png)
