### ISSUE TITLE
Phonecat in AngularJS-Eclipse, and 'bower'

### ISSUE THREAD

**Issue by pivan9911** [angelozerr/angularjs-eclipse#211]
Hello Angello Zerr.

I tried to use Eclipse-Neon with Angularjs-Eclipse plugin,   to make the 
Angular-Phonecat tutorial working in Eclipse.
 
I cannot decide how to provide unresolved 'bower_components',  that are required in index.html.

    <title>Google Phone Gallery</title>
    <link rel="stylesheet" href="**bower_components**/bootstrap/dist/css/bootstrap.css" />
    <script                          src="**bower_components/**jquery/dist/jquery.js"></script>

Can npm in AngularJS-Eclipse be configured, to invoke 'bower'  ??

I tried also  Project. "Run As"    Bower-Install,       this gave:
   'bower' is not recognized as an internal or external command,

Any Idea welcome.
 
 Kind regards
   I. Pea
   

http://oss.opensagres.fr/angularjs-eclipse/1.2.0/
https://docs.angularjs.org/tutorial
https://www.npmjs.com/package/bower

**Comment by pivan9911** [comment]
On Windows 10,  I installed node.js (containing npm) and also bower (npm install -g bower).
Git installation was also needed.   
angular-phonecat/bower.json   ( run-a  bower-install,    works :-)

How does one now,  start execution of this thing ?

**Comment by angelozerr** [comment]
This issue is about bower which comes from Eclipse Neon, please post your question to Eclipse forum. Thanks
