### ISSUE TITLE
Error when creating Angular2 project

### ISSUE THREAD

**Issue by moonki-cho** [angelozerr/angularjs-eclipse#214]
hello

my computer is a mac(os x el capitan) and using zsh(shell), Neon(4.6)

I am trying to create an angular2 project, but I get an error when I run the “npm install angular-cli@1.0.0-beta.22-1″ command.

The error message displayed on the terminal is “/bin/zsh: no such option: rcfile”.

(There is nothing wrong with the Mac terminal.)

I’d appreciate it if you could give me a solution.

**Comment by jludvice** [comment]
Hello, I have the same issue when I try to import existing Angular project into eclipse.

**Comment by angelozerr** [comment]
This repository is for AngularJS and not for Angular2. Please report issue at https://github.com/angelozerr/angular2-eclipse

> The error message displayed on the terminal is “/bin/zsh: no such option: rcfile”.

Using npm is not managed by Angular2 Eclipse, but Angular2 Eclipse provides a wizard to generate Angular2 Project, please install 1.2.0 angular2 eclipse https://github.com/angelozerr/angular2-eclipse/wiki/Installation-Update-Site
