### ISSUE TITLE
Angular2 IDE Plugin Issue

### ISSUE THREAD

**Issue by mailtoab** [angelozerr/angularjs-eclipse#217]
hello @angelozerr

I have installed node and angular-cli.
After that while installing angular2 plugin on Neon Eclipse, getting the following error:
 
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/angular2-eclipse/1.1.0/plugins/ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64_1.1.0.201611012122.jar.
Premature end of Content-Length delimited message body (expected: 5614836; received: 3459582
Unable to read repository at http://oss.opensagres.fr/angular2-eclipse/1.1.0/plugins/ts.repository_1.1.0.201611012122.jar.
Premature end of Content-Length delimited message body (expected: 3698906; received: 565502

HTTP directory
http://oss.opensagres.fr/angular2-eclipse/1.1.0/

Please help.

**Comment by angelozerr** [comment]
Your issue is for https://github.com/angelozerr/angular2-eclipse/issues

Our server is a little slow, so you can have this trouble (according some countries). I suggest you that you try to download local update site https://github.com/angelozerr/angular2-eclipse/releases

**Comment by mailtoab** [comment]
Awesome @angelozerr.
After installation, I created angular2 project in eclipse. It is taking long time to download node modules. What is the reason?

**Comment by angelozerr** [comment]
It's @angular/cli which download node modules. If you open a System terminal (without eclipse), you will have the same problem.

If you need more info, please post your question to angular/cli github project.

**Comment by mailtoab** [comment]
Thanks again @angelozerr.
I have created the following issue, Is it the right place?
https://github.com/angular/angular-cli/issues/5415

**Comment by angelozerr** [comment]
@mailtoab 1.1.0 uses the old version of angular cli "angular-cli". 

Today you must use "@angular/cli" which is supported by Angular2 Eclipse 1.2.0-SNAPSHOT.

I close this issue because it's not the Angular2 project  https://github.com/angelozerr/angular2-eclipse/issues

**Comment by mailtoab** [comment]
I don't get this.  What should I do now to install @angular/cli?
