### ISSUE TITLE
Angular2 Eclipse

### ISSUE THREAD

**Issue by mailtoab** [angelozerr/angularjs-eclipse#218]
@angelozerr 

Do you have local update site for angular2 eclipse plugin
Angular2 Eclipse 1.2.0-SNAPSHOT?

**Comment by angelozerr** [comment]
@mailtoab your issues are about Angular2 Eclipse and not AngularJS Eclipse. Please create your issues at https://github.com/angelozerr/angular2-eclipse/issues

Thanks!
