### ISSUE TITLE
Could Not find the required bundle org.eclipse.wst.html.core;bundle-version="1.2.0"

### ISSUE THREAD

**Issue by sudeep30m** [angelozerr/angularjs-eclipse#221]
Sir,

I am working on the extension of your plugin to add the static analysis tool - slicing in it. I could not find the required bundle org.eclipse.wst.html.core;bundle version="1.2.0" due to which Eclipse could not resolve module org.eclipse.angularjs.core and other modules depending on it. It would be of great help if you can provide me the jar file of the bundle.

**Comment by angelozerr** [comment]
Install Eclipse Jee Neon and you should have this plugin.
